from will.plugin import WillPlugin
from will.decorators import respond_to, periodic, hear, randomly, route, rendered_template, require_settings
from random import randint

class ComplimentPlugin(WillPlugin):

    @respond_to("compliment me")
    def compliment(self, message):
        """compliment me: I can compliment you!"""

        comp = compliments[randint(0, len(compliments)-1)]

        self.reply(message, comp)

    @respond_to("trashtalk me")
    def trashtalk(self, message):
        """trashtalk me: I can insult you!"""

        trashtalk = insults[randint(0, len(insults)-1)]

        self.reply(message, trashtalk)

compliments = ["You have very smooth hair.",
"You deserve a promotion.",
"Good effort!",
"What a fine sweater!",
"I appreciate all of your opinions.",
"I like your style.",
"Your T-shirt smells fresh.",
"I love what you've done with the place.",
"You are like a spring flower; beautiful and vivacious.",
"I am utterly disarmed by your wit.",
"I really enjoy the way you pronounce the word 'ruby'.",
"You complete me.",
"Well done!",
"I like your Facebook status.",
"That looks nice on you.",
"I like those shoes more than mine.",
"Nice motor control!",
"You have a good taste in websites.",
"Your mouse told me that you have very soft hands.",
"You are full of youth.",
"I like your jacket.",
"I like the way you move.",
"You have a good web-surfing stance.",
"You should be a poster child for poster children.",
"Nice manners!",
"I appreciate you more than Santa appreciates chimney grease.",
"I wish I was your mirror.",
"I find you to be a fountain of inspiration.",
"You have perfect bone structure.",
"I disagree with anyone who disagrees with you.",
"Way to go!",
"Have you been working out?",
"With your creative wit, I'm sure you could come up with better compliments than me.",
"I like your socks.",
"You are so charming.",
"Your cooking reminds me of my mother's.",
"You're tremendous!",
"You deserve a compliment!",
"Hello, good looking.",
"Your smile is breath taking.",
"How do you get your hair to look that great?",
"You are quite strapping.",
"I am grateful to be blessed by your presence.",
"Say, aren't you that famous model from TV?",
"Take a break; you've earned it.",
"Your life is so interesting!",
"The sound of your voice sends tingles of joy down my back.",
"I enjoy spending time with you.",
"I would share my dessert with you.",
"You can have the last bite.",
"May I have this dance?",
"I would love to visit you, but I live on the Internet.",
"I love the way you click.",
"You're invited to my birthday party.",
"All of your ideas are brilliant!",
"If I freeze, it's not a computer virus.  I was just stunned by your beauty.",
"You're spontaneous, and I love it!",
"You should try out for everything.",
"You make my data circuits skip a beat.",
"You are the gravy to my mashed potatoes.",
"You get an A+!",
"I'm jealous of the other websites you visit, because I enjoy seeing you so much!",
"I would enjoy a roadtrip with you.",
"If I had to choose between you or Mr. Rogers, it would be you.",
"I like you more than the smell of Grandma's home-made apple pies.",
"You would look good in glasses OR contacts.",
"Let's do this again sometime.",
"You could go longer without a shower than most people.",
"I feel the need to impress you.",
"I would trust you to pick out a pet fish for me.",
"I'm glad we met.",
"Do that again!",
"Will you sign my yearbook?",
"You're so smart!",
"We should start a band.",
"You're cooler than ice-skating Fonzi.",
"I made this website for you.",
"I heard you make really good French Toast.",
"You're cooler than Pirates and Ninjas combined.",
"Oh, I can keep going.",
"I like your pants.",
"You're pretty groovy, dude.",
"When I grow up, I want to be just like you.",
"I told all my friends about how cool you are.",
"You can play any prank, and get away with it.",
"You have ten of the best fingers I have ever seen!",
"I can tell that we are gonna be friends.",
"I just want to gobble you up!",
"You're sweeter than than a bucket of bon-bons!",
"Treat yourself to another compliment!",
"You're pretty high on my list of people with whom I would want to be stranded on an island.",
"You're #1 in my book!",
"Well played.",
"You are well groomed.",
"You could probably lead a rebellion.",
"Is it hot in here or is it just you?",
"<3",
"You are more fun than a Japanese steakhouse.",
"Your voice is more soothing than Morgan Freeman's.",
"I like your sleeves. They're real big.",
"You could be drinking whole milk if you wanted to.",
"You're so beautiful, you make me walk into things when I look at you.",
"I support all of your decisions.",
"You are as fun as a hot tub full of chocolate pudding.",
"I usually don't say this on a first date, but will you marry me?",
"I don't speak much English, but with you all I really need to say is beautiful.",
"Being awesome is hard, but you'll manage.",
"Your skin is radiant.",
"You will still be beautiful when you get older.",
"You could survive a zombie apocalypse.",
"You make me :)",
"I wish I could move your furniture.",
"I think about you while I'm on the toilet.",
"You're so rad.",
"You're more fun than a barrel of monkeys.",
"You're nicer than a day on the beach.",
"Your glass is the fullest.",
"I find you very relevant.",
"You look so perfect.",
"The only difference between exceptional and amazing is you.",
"Last night I had the hiccups, and the only thing that comforted me to sleep was repeating your name over and over.",
"I like your pearly whites!",
"Your eyebrows really make your pretty eyes stand out.",
"Shall I compare thee to a summer's day?  Thou art more lovely and more temperate.",
"I love you more than bacon!",
"You intrigue me.",
"You make me think of beautiful things, like strawberries.",
"I would share my fruit Gushers with you.",
"You're more aesthetically pleasant to look at than that one green color on this website.",
"Even though this goes against everything I know, I think I'm in love with you.",
"You're more fun than bubble wrap.",
"Your smile could illuminate the depths of the ocean.",
"You make babies smile.",
"You make the gloomy days a little less gloomy.",
"You are warmer than a Snuggie.",
"You make me feel like I am on top of the world.",
"Playing video games with you would be fun.",
"Let's never stop hanging out.",
"You're more cuddly than the Downy Bear.",
"I would do your taxes any day.",
"You are a bucket of awesome.",
"You are the star of my daydreams.",
"If you really wanted to, you could probably get a bird to land on your shoulder and hang out with you.",
"My mom always asks me why I can't be more like you.",
"You look great in this or any other light.",
"You listen to the coolest music.",
"You and Chuck Norris are on equal levels.",
"Your body fat percentage is perfectly suited for your height.",
"I am having trouble coming up with a compliment worthy enough for you.",
"If we were playing kickball, I'd pick you first.",
"You're cooler than ice on the rocks.",
"You're the bee's knees.",
"I wish I could choose your handwriting as a font.",
"You definitely know the difference between your and you're.",
"You have good taste.",
"I named all my appliances after you.",
"Your mind is a maze of amazing!",
"Don't worry about procrastinating on your studies, I know you'll do great!",
"I like your style!",
"Hi, I'd like to know why you're so beautiful.",
"If I could count the seconds I think about you, I will die in the process!",
"If you were in a chemistry class with me, it would be 10x less boring.",
"If you broke your arm, I would carry your books for you.",
"I love the way your eyes crinkle at the corners when you smile.",
"You make me want to be the person I am capable of being.",
"You're a skilled driver.",
"You are the rare catalyst to my volatile compound.",
"You're a tall glass of water!",
"I'd like to kiss you. Often.",
"You are the wind beneath my wings.",
"Looking at you makes my foot cramps go away instantaneously.",
"I like your face.",
"You are a champ!",
"You are infatuating.",
"Even my cat likes you.",
"There isn't a thing about you that I don't like.",
"You're so cool, that on a scale of from 1-10, you're elevendyseven.",
"OH, you OWN that ponytail.",
"Your shoes are untied. But for you, it's cool.",
"You have the best laugh ever.",
"We would enjoy a cookout with you!",
"Your name is fun to say.",
"I love you more than a drunk college student loves tacos.",
"My camera isn't worthy to take your picture.",
"You are the sugar on my rice krispies.",
"Nice belt!",
"I could hang out with you for a solid year and never get tired of you.",
"You're real happening in a far out way.",
"I bet you could take a punch from Mike Tyson.",
"Your feet are perfect size!",
"You have very nice teeth.",
"Can you teach me how to be as awesome as you?",
"Our awkward silences aren't even awkward.",
"Don't worry. You'll do great.",
"I enjoy you more than a good sneeze. A GOOD one.",
"You could invent words and people would use them.",
"You have powerful sweaters.",
"If you were around, I would enjoy doing my taxes.",
"You look like you like to rock.",
"You are better than unicorns and sparkles combined!",
"You are the watermelon in my fruit salad. Yum!",
"I dig you.",
"You look better whether the lights are on or off.",
"I am enchanted to meet you.",
"I bet even your farts smell good.",
"I would trust my children with you.",
"You make me forget what I was going to...",
"Your smile makes me smile.",
"I'd wake up for an 8 a.m. class just so I could sit next to you.",
"You have the moves like Jagger.",
"You're so hot that you denature my proteins.",
"All I want for Christmas is you!",
"You are the world's greatest hugger.",
"You have a perfectly symmetrical face.",
"If you were in a movie you wouldn't get killed off.",
"Your red ruby lips and wiggly hips make me do flips!",
"I definitely wouldn't kick you out of bed.",
"They should name an ice cream flavor after you.",
"You're the salsa to my tortilla chips. You spice up my life!",
"You smell nice.",
"You don't need make-up, make-up needs you.",
"Me without you is like a nerd without braces, a shoe with out laces, asentencewithoutspaces.",
"Just knowing someone as cool as you will read this makes me smile.",
"I would volunteer to take your place in the Hunger Games.",
"If I had a nickel for everytime you did something stupid, I'd be broke!",
"I'd let you steal the white part of my Oreo.",
"I'd trust you to perform open heart surgery on me... blindfolded!",
"Nice butt! - According to your toilet seat",
"Perfume strives to smell like you.",
"I've had the time of my life, and I owe it all to you!",
"The Force is strong with you.",
"I like the way your nostrils are placed on your nose.",
"I would hold the elevator doors open for you if they were closing.",
"Your every thought and motion contributes to the beauty of the universe.",
"You make me want to frolic in a field. "]

insults = [
    "You look like you're going to spend your life having one epiphany after another, always thinking you've finally figured out what's holding you back, and how you can finally be productive and creative and turn you life around. But nothing will ever change. That cycle of mediocrity isn't due to some obstacle. It's who you are. The thing standing in the way of your dreams is that the person having them is you.",
    "I hope you realize everyone's just putting up with you.",
    "If I was locked in a room with Stalin, Hitler, and you, and had a gun with only 2 bullets, I'd shoot you twice.",
    "Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology.",
    "I don't have the time nor crayons to explain this on your level.",
    "I wish we were better strangers.",
    "Your mother was a hamster and your father smells of elderberries.",
    "It looks like your face caught fire and someone tried to put it out with a bicycle chain.",
    "Your IQ doesn't make a respectable earthquake.",
    "Your mom's so fat that her Patronus is a cake.",
    "Isn't it rather dangerous to use one's entire vocabulary in a single sentence?",
    "You should eat some of your make up so you can be pretty on the inside.", 
    "I'm jealous of people that don't know you!",
    "A nerd is at least smart.",
    "So a thought crossed your mind? Must have been a long and dangerous journey.",
    "It's scary to think that people like you are allowed to vote.",
    "Don't let your mind wander. It's too small to be out there on its own.",
    "I don't hate you, but if you were on fire and I had water, I'd drink it.",
    "If I wanted to kill myself, I'd climb to your ego and jump to your IQ.",
    "You are at the top of the bell curve.",
    "Well I could agree with you, but then we'd both be wrong.",
    "If you spoke your find, you'd be speechless.",
    "It's better to let someone think you are an idiot than to open your mouth and prove it.",
    "I hope the rest of your day is as pleasant as you are.",
    "Did you fall from heaven? Cause you face is messed up!",
    "You're the personificiation of Comic Sans.",
    "You're the reason they only have McRibs a certain time of the year. :(",
    "You are so stupid, you'd trip over a cordless phone.",
    "If you're gonna be a smartass, first you have to be smart. Otherwise you're just an ass.",
    "I'll never forget the first time we met, although I'll keep trying.",
    "So you've changed your mind, does this one work any better?",
    "I heard you went to a haunted house and they offered you a job.",
    "You stare at frozen juice cans because they say, 'concentrate'.",
    "I don't know what makes you so stupid, but it really works!",
    "Aww, it's so cute when you try to talk about things you don't understand.",
    "You have the perfect face for radio.",
    "If brains were dynamite you wouldn't have enough to blow your nose.",
    "I've seen people like you, but I had to pay admission!",
    "Brains aren't everything. In your case they're nothing.",
    "You must be the arithmetic man; you add trouble, subtract pleasure, divide attention, and multiply ignorance.",
    "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
    "I'd like to help you out. Which way did you come in?",
    "You must think you're strong, but you only smell strong.",
    "If you are going to be two faced, at least make one of them pretty.",
    "You're so stupid you tried to wake a sleeping bag.",
    "You shouldn't play hide and seek, no one would look for you.",
    "You have a very sympathetic face. It has everyone's sympathy.",
    "Do you even have a demo for this week?",
    "Why doesn't your website use any Bootstrap?",
    "You're so ugly, the only dates you get are on a calendar.",
    "If you had another brain, it would be lonely.",
    "You're not exactly bad looking. There's just one little problem between your ears - your face!",
    "Looks aren't everything; in your case, they aren't anything!",
    "You must be on the seafood diet. When you see food, you eat it!",
    "Yeah, you're pretty stupid.",
    "You are so incomprehensibly stupid, I am honestly baffled that you somehow have managed to go this long without forgetting how to breathe.",
    "You are living proof that natural selection doesn't always work. Statistically speaking, you should have been eaten by wolves over a decade ago.",
    "I hope you step on a Lego.",
    "I bite my thumb at you.",
    "I hope you are brought to the top of a cliff by the person you love most in the world, and they push you off. And as you accept your mortality and make peace with it, the instant before you hit the ground, Superman comes out of nowhere and saves you. He then flies into the air, and drops you from even higher.",
    "I refuse to have a battle of wits with an unarmed man."
    ]